### PR TITLE
When no font filename is found, determine extension automatically

### PR DESCRIPTION
**Pull request by FTWinston**
When a font is downloaded from a url that doesn't have a filename for it, the font is saved with a filename that is a hash of its url.

That doesn't work for my (webpack) use case, because I'd like to still be able to give the filename an appropriate file extension in this scenario.

This PR uses the content-type header to decide a filename. I had considered using the filename within the content-disposition header, but google fonts calls them all "font" still (e.g. font.woff2, font.ttf) so that doesn't work with multiple fonts.

This involved more refactoring than I'd hoped, as previously the filename was known before the download started. Annoyingly, the declaration now needs to be passed around with the job, so it can be updated once the file name has been determined.

### CODE REVIEW

**Comment by FTWinston** [comment]
Let me know if you'd like me to clarify or rework anything here, I don't want to rush it in and have it break things.

**Comment by AaronJan** [comment]
@FTWinston What a coincidence. 😃  I'm planning to write some intergration tests that put postcss-font-grabber works together with Webpack, Gulp (etc.), I think these tests could help solve this issue (or prevents regression).

Could you provide some code to reproduce this problem? Let's recreate these scenarios first.

What you think?

**Comment by AaronJan** [comment]
I'm gonna catch some sleep now (it's very late here). 💤

**Comment by FTWinston** [comment]
Can do, Shall I add an examplar webpack config on a separate PR, or would its own repo be easier?

**Comment by AaronJan** [comment]
@FTWinston I'm sorry, just got off work... I'm planning just put some examples in this repo and verify them via GitHub Action.

Will start tomorrow by adding a basic one (I hope), we can add more examples then.

**Comment by AaronJan** [comment]
@FTWinston FYI, I'm currently migrating to PostCSS v8, doesn't v8 works for you?

**Comment by FTWinston** [comment]
Sorry, other things have kept me from getting that webpack example put together. I'll get it in the next day or two.

I think I had to target v7 to avoid an error when running the tests locally, I forget what exactly went wrong but I think it mentioned the postcss version. I'll check and get back to you. (I'm super-new to postcss though.)

**Comment by AaronJan** [comment]
> Sorry, other things have kept me from getting that webpack example put together. I'll get it in the next day or two.
> 
> I think I had to target v7 to avoid an error when running the tests locally, I forget what exactly went wrong but I think it mentioned the postcss version. I'll check and get back to you. (I'm super-new to postcss though.)

Cool, if you have to use v7, please let me know.

**Comment by AaronJan** [comment]
@FTWinston FYI, I'm currently rewrite the whole project (as v3.x), it might need another a couple days.

**Comment by AaronJan** [comment]
@FTWinston `v3` been published, I think it solves this issue? 

Please give it a try when it's possible, or take a look at the code to verify it.

If you have any thoughts / sugguestions, please let me know at #17. 😃

**Comment by FTWinston** [comment]
Brilliant, thanks. I'll try this in our project tomorrow and report back.

**Comment by FTWinston** [comment]
This looks great, and does download google font files with the correct extension now, thanks! I've run into some further issues, but this PR is no longer relevant, happy to close.

**Comment by AaronJan** [comment]
> This looks great, and does download google font files with the correct extension now, thanks! I've run into some further issues, but this PR is no longer relevant, happy to close.

It's a pleasure! I'll ping you when a standard version is ready. 🤝

**Pull request closed without merging**
